server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: users_payments
    password: users_payments
    virtual-host: /

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/users_payments
    username: users_payments
    password: users_payments
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}


messaging:
  userCreated:
    exchange: user.managing.tx
    routingKey: created
    queue: user.created.queue
  userUpdated:
    exchange: user.managing.tx
    routingKey: updated
    queue: user.updated.queue
  paymentCreated:
    exchange: payment.managing.tx
    routingKey: created
    queue: payment.created.queue

management:
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    tags:
      application: UsersPaymentsSinkApplication