server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: users_payments
    password: users_payments
    virtual-host: /

messaging:
  paymentExternalCreated:
    exchange: payment.external.managing.tx
    routingKey: created
    queue: payment.external.created.queue
  paymentCreated:
    exchange: payment.managing.tx
    routingKey: created

management:
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    tags:
      application: UsersPaymentsSinkApplication